<?php

namespace ApiBundle\Entity\Repository;

/**
 * IndustrySectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustrySectorRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllOrderedByName() {
          return $this->getEntityManager()
              ->createQuery(
                  'SELECT i FROM ApiBundle:IndustrySector i ORDER BY i.name ASC'
              )
              ->getResult();
      }
}
